pkg/plugin/view/kubehunter/report_view.go

Add summary section to the kube-hunter report component - https://github.com/aquasecurity/starboard-octant-plugin/issues/27.

chore: Update summary in kube-hunter

---

pkg/plugin/view/links.go
pkg/plugin/view/vulnerabilities/report_view.go

fix: Broken links in vulnerability report

---

.github/workflows/build.yaml
Makefile
go.mod
pkg/plugin/view/vulnerabilities/report_view.go
pkg/plugin/view/vulnerabilities/sort.go
pkg/plugin/view/vulnerabilities/sort_test.go

feat: Order vulnerability items by severity

---

README.md

docs(README): Add GitHub all releases download badge

---

pkg/plugin/model/repository.go

feat: Do not use latest history label on CISKubeBenchReport resources

---

.goreleaser.yaml

chore: Build release artifacts for Windows

---

go.mod
go.sum
pkg/plugin/model/repository.go
pkg/plugin/view/kubebench/report_view.go
pkg/plugin/view/vulnerabilities/report_view.go
pkg/plugin/view/vulnerabilities/sort.go
pkg/plugin/view/vulnerabilities/sort_test.go

refactor: Change Vulnerability kind to VulnerabilityReport

---

go.mod
go.sum

chore: Bump up starboard to v0.4.0

---

README.md
go.mod
go.sum
pkg/plugin/view/configaudit/report_view.go
pkg/plugin/view/kubehunter/report_view.go

feat: Display summaries from ConfigAuditReport and KubeHunterReport resources

---

pkg/plugin/controller/printers.go
pkg/plugin/view/kubebench/report_view.go

fix: Check if CISKubeBenchReport CR is defined

---

pkg/plugin/controller/root.go
pkg/plugin/view/kubehunter/report_view.go

fix: Check if KubeHunterReport CR is defined

---

pkg/plugin/controller/printers.go
pkg/plugin/model/repository.go
pkg/plugin/view/configaudit/summary.go

feat: Display config audit summary

---

.github/workflows/build.yaml
.github/workflows/release.yaml
go.mod
go.sum
pkg/plugin/view/configaudit/report_view.go
pkg/plugin/view/vulnerabilities/report_view.go

chore: Bump up dependency starboard from v0.6.0 to v0.7.0

---

go.mod
go.sum

chore: Bump up octant from v0.16.1 to 0.16.3

---

pkg/plugin/view/configaudit/report_view.go
pkg/plugin/view/configaudit/summary.go
pkg/plugin/view/kubebench/report_view.go
pkg/plugin/view/kubehunter/report_view.go
pkg/plugin/view/vulnerabilities/report_view.go
pkg/plugin/view/vulnerabilities/summary_sections_view.go

fix: Do not use deprecated commands in examples

---

.github/workflows/build.yaml
.github/workflows/release.yaml
README.md
pkg/plugin/view/configaudit/report_view.go
pkg/plugin/view/kubebench/report_view.go
pkg/plugin/view/kubehunter/report_view.go
pkg/plugin/view/vulnerabilities/report_view.go

chore: Switch to main branch

---

go.mod
go.sum

chore: Bump up starboard from v0.7.0 to v0.8.0

---

go.mod
go.sum

release: Prepare v0.9.0

---

pkg/plugin/controller/printers.go
pkg/plugin/model/repository.go

fix: Resolve ConfigAuditReport for any object in the same hierarchy

---

pkg/plugin/view/configaudit/report_view.go
pkg/plugin/view/configaudit/report_view_test.go

feat: Render configuration audit checks with status icons

---

go.mod
go.sum

chore: Bump up Octant to v0.20.0
